//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAV.UniverseCleaning.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAV.UniverseCleaning.App_LocalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string AboutUsDescription {
            get {
                return ResourceManager.GetString("AboutUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string AboutUsKeywords {
            get {
                return ResourceManager.GetString("AboutUsKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutUsTitle {
            get {
                return ResourceManager.GetString("AboutUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string AfterBuildersCleaningKeywords {
            get {
                return ResourceManager.GetString("AfterBuildersCleaningKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string AfterBuildersDescription {
            get {
                return ResourceManager.GetString("AfterBuildersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services - After Builders Cleaning.
        /// </summary>
        public static string AfterBuildersTitle {
            get {
                return ResourceManager.GetString("AfterBuildersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string CarpetCleaningDescription {
            get {
                return ResourceManager.GetString("CarpetCleaningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string CarpetCleaningKeywords {
            get {
                return ResourceManager.GetString("CarpetCleaningKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services - Carpet Cleaning.
        /// </summary>
        public static string CarpetCleaningTitle {
            get {
                return ResourceManager.GetString("CarpetCleaningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string ComercialServiceDescription {
            get {
                return ResourceManager.GetString("ComercialServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string ComercialServiceKeywords {
            get {
                return ResourceManager.GetString("ComercialServiceKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services - Comercial Service.
        /// </summary>
        public static string ComercialServiceTitle {
            get {
                return ResourceManager.GetString("ComercialServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Address:.
        /// </summary>
        public static string ContactUsAddressTitle {
            get {
                return ResourceManager.GetString("ContactUsAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string ContactUsDescription {
            get {
                return ResourceManager.GetString("ContactUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string ContactUsKeywords {
            get {
                return ResourceManager.GetString("ContactUsKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactUsMessage {
            get {
                return ResourceManager.GetString("ContactUsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactUsTitle {
            get {
                return ResourceManager.GetString("ContactUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string CustomerSatisfactionDescription {
            get {
                return ResourceManager.GetString("CustomerSatisfactionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string CustomerSatisfactionKeywords {
            get {
                return ResourceManager.GetString("CustomerSatisfactionKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Satisfaction.
        /// </summary>
        public static string CustomerSatisfactionTitle {
            get {
                return ResourceManager.GetString("CustomerSatisfactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string DomesticCleaningDescription {
            get {
                return ResourceManager.GetString("DomesticCleaningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services - Domestic Cleaning.
        /// </summary>
        public static string DomesticCleaningTitle {
            get {
                return ResourceManager.GetString("DomesticCleaningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string DomesticServiceKeywords {
            get {
                return ResourceManager.GetString("DomesticServiceKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string EndOfTenancyCleaningDescription {
            get {
                return ResourceManager.GetString("EndOfTenancyCleaningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services - End of Tenancy Cleaning.
        /// </summary>
        public static string EndOfTenancyCleaningTitle {
            get {
                return ResourceManager.GetString("EndOfTenancyCleaningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string EndOfTenancyKeywords {
            get {
                return ResourceManager.GetString("EndOfTenancyKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universe Cleaning offers a flexible home cleaning service at an affordable price (no matter whether a house or a flat clean is required), based on a no-obligation, free estimate carried out in your home. Uniformed, fully insured staff typically work in teams of two to efficiently clean your home..
        /// </summary>
        public static string HomeDescription {
            get {
                return ResourceManager.GetString("HomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string HomeKeywords {
            get {
                return ResourceManager.GetString("HomeKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Universe Cleaning.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string IroningAtHomeDescription {
            get {
                return ResourceManager.GetString("IroningAtHomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string IroningAtHomeKeywords {
            get {
                return ResourceManager.GetString("IroningAtHomeKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services - Ironing at your Home.
        /// </summary>
        public static string IroningAtHomeTitle {
            get {
                return ResourceManager.GetString("IroningAtHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string OffersDescription {
            get {
                return ResourceManager.GetString("OffersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OffersMessage {
            get {
                return ResourceManager.GetString("OffersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Offers.
        /// </summary>
        public static string OffersTitle {
            get {
                return ResourceManager.GetString("OffersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string OvenCleaningDescription {
            get {
                return ResourceManager.GetString("OvenCleaningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string OvenCleaningKeywords {
            get {
                return ResourceManager.GetString("OvenCleaningKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services - Oven Cleaning.
        /// </summary>
        public static string OvenCleaningTitle {
            get {
                return ResourceManager.GetString("OvenCleaningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string ServicesDescription {
            get {
                return ResourceManager.GetString("ServicesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string ServicesKeywords {
            get {
                return ResourceManager.GetString("ServicesKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string ServicesTitle {
            get {
                return ResourceManager.GetString("ServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://universecleaning.azurewebsites.net/.
        /// </summary>
        public static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string SpecialOffersKeywords {
            get {
                return ResourceManager.GetString("SpecialOffersKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string SpringCleanDescription {
            get {
                return ResourceManager.GetString("SpringCleanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string SpringCleaningKeywords {
            get {
                return ResourceManager.GetString("SpringCleaningKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services - Spring Clean.
        /// </summary>
        public static string SpringCleanTitle {
            get {
                return ResourceManager.GetString("SpringCleanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string TestimonialsDescription {
            get {
                return ResourceManager.GetString("TestimonialsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string TestimonialsKeywords {
            get {
                return ResourceManager.GetString("TestimonialsKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        public static string TestimonialsTitle {
            get {
                return ResourceManager.GetString("TestimonialsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string WhyUsDescription {
            get {
                return ResourceManager.GetString("WhyUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Stortford Cleaning, Bishop Cleaning, Cheshunt Cleaning, Hertford Cleaning, Hoddeston Cleaning, Harlow Cleaning, Roydon Cleaning, Broxborne Cleaning.
        /// </summary>
        public static string WhyUsKeywords {
            get {
                return ResourceManager.GetString("WhyUsKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Us.
        /// </summary>
        public static string WhyUsTitle {
            get {
                return ResourceManager.GetString("WhyUsTitle", resourceCulture);
            }
        }
    }
}
